apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bedrock-database
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/sassendes/bedrock.git
    targetRevision: main
    path: database
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - RespectIgnoreDifferences=true
