apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-1-scheduled-backup
  namespace: cluster-1
spec:
  schedule: "0 0 */6 * * *"
  immediate: false
  backupOwnerReference: self
  cluster:
    name: cluster-1
  method: barmanObjectStore
