apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: cluster-1-initial
  namespace: cluster-1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: cluster-1
  method: barmanObjectStore
