apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: cluster-1
type: Opaque
stringData:
  ACCESS_KEY_ID: minioadmin
  SECRET_ACCESS_KEY: minioadmin
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: cluster-2
type: Opaque
stringData:
  ACCESS_KEY_ID: minioadmin
  SECRET_ACCESS_KEY: minioadmin
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: cluster-3
type: Opaque
stringData:
  ACCESS_KEY_ID: minioadmin
  SECRET_ACCESS_KEY: minioadmin
