apiVersion: v1
kind: Namespace
metadata:
  name: cluster-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-2
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-3
---
apiVersion: v1
kind: Namespace
metadata:
  name: application
