apiVersion: v1
kind: Secret
metadata:
  name: super-secret-1
  namespace: cluster-1
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres  # u need to change this or use sops
