apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: application
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
      aws:
        s3: http://lokiadmin:lokiadmin@loki-minio.application.svc:9000/loki-data
        s3forcepathstyle: true
    limits_config:
      retention_period: 720h
    compactor:
      working_directory: /loki/compactor
      retention_enabled: true
      delete_request_store: s3
    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: application
  labels:
    app: loki
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.2.1
          args: ["-config.file=/etc/loki/loki.yaml"]
          ports:
            - containerPort: 3100
              name: http
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: application
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
