apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter
  namespace: application
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200]
          method: GET
      tcp_connect:
        prober: tcp
        timeout: 5s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: application
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: quay.io/prometheus/blackbox-exporter:v0.25.0
          args:
            - --config.file=/etc/blackbox/blackbox.yml
          ports:
            - containerPort: 9115
              name: metrics
          resources:
            requests:
              memory: 32Mi
              cpu: 25m
            limits:
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: application
  labels:
    app: blackbox-exporter
spec:
  selector:
    app: blackbox-exporter
  ports:
    - name: metrics
      port: 9115
      targetPort: 9115
