apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-1
  namespace: cluster-1
spec:
  monitoring:
    enablePodMonitor: true
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  storage:
    size: 10Gi
    storageClass: longhorn
  enableSuperuserAccess: true
  superuserSecret:
    name: super-secret-1
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"
  bootstrap:
    initdb:
      database: app
      owner: appuser
      secret:
        name: user-secret-1
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pgcrypto;
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
  backup:
    barmanObjectStore:
      destinationPath: s3://cluster-1-backups/wals
      endpointURL: http://minio.cluster-1.svc:9000
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
