apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: cluster-1-pooler-rw
  namespace: cluster-1
spec:
  cluster:
    name: cluster-1
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: cluster-2-pooler-rw
  namespace: cluster-2
spec:
  cluster:
    name: cluster-2
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
---
# warm spare
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: cluster-3-pooler-rw
  namespace: cluster-3
spec:
  cluster:
    name: cluster-3
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "25"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-rw
  namespace: application
  labels:
    bedrock.io/points-at: cluster-1
spec:
  type: ExternalName
  externalName: cluster-1-pooler-rw.cluster-1.svc.cluster.local
  ports:
    - name: postgres
      port: 5432
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cluster-1-pooler-rw
  namespace: cluster-1
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/poolerName: cluster-1-pooler-rw
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cluster-2-pooler-rw
  namespace: cluster-2
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/poolerName: cluster-2-pooler-rw
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cluster-3-pooler-rw
  namespace: cluster-3
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/poolerName: cluster-3-pooler-rw
