apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:background-controller:bedrock-secrets
  labels:
    rbac.kyverno.io/aggregate-to-background-controller: "true"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:admission-controller:bedrock-secrets
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: bedrock-replica-secret-sync
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  rules:
    - name: clone-cluster-1-ca
      match:
        any:
          - resources:
              kinds: [Namespace]
              names: [cluster-2, cluster-3]
      generate:
        generateExisting: true
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: cluster-1-ca
        namespace: "{{request.object.metadata.name}}"
        clone:
          namespace: cluster-1
          name: cluster-1-ca
    - name: clone-cluster-1-replication
      match:
        any:
          - resources:
              kinds: [Namespace]
              names: [cluster-2, cluster-3]
      generate:
        generateExisting: true
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: cluster-1-replication
        namespace: "{{request.object.metadata.name}}"
        clone:
          namespace: cluster-1
          name: cluster-1-replication
    - name: clone-cluster-1-backups
      match:
        any:
          - resources:
              kinds: [Namespace]
              names: [cluster-2, cluster-3]
      generate:
        generateExisting: true
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: cluster-1-backups
        namespace: "{{request.object.metadata.name}}"
        clone:
          namespace: cluster-1
          name: cluster-1-backups
 
