apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: cluster-1-backups
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: cluster-1
spec:
  bucketName: cluster-1-backups
  storageClassName: bedrock-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: cluster-2-backups
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: cluster-2
spec:
  bucketName: cluster-2-backups
  storageClassName: bedrock-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: cluster-3-backups
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: cluster-3
spec:
  bucketName: cluster-3-backups
  storageClassName: bedrock-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-data
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: application
spec:
  bucketName: loki-data
  storageClassName: bedrock-bucket
