apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: bedrock-s3
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    replicated:
      size: 3
  preservePoolsOnDelete: true
  gateway:
    port: 80
    instances: 2
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bedrock-bucket
  annotations:
    argocd.argoproj.io/sync-wave: "1"
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Retain
parameters:
  objectStoreName: bedrock-s3
  objectStoreNamespace: rook-ceph
