apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: application
data:
  server.yml: |
    base-url: "http://localhost"
    cache-file: "/var/lib/ntfy/cache.db"
    auth-file: "/var/lib/ntfy/auth.db"
    auth-default-access: "deny-all"
    behind-proxy: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data
  namespace: application
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: application
  labels:
    app: ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:v2.11.0
          args: ["serve"]
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 32Mi
              cpu: 25m
            limits:
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /etc/ntfy
            - name: data
              mountPath: /var/lib/ntfy
      volumes:
        - name: config
          configMap:
            name: ntfy-config
        - name: data
          persistentVolumeClaim:
            claimName: ntfy-data
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: application
  labels:
    app: ntfy
spec:
  type: NodePort
  selector:
    app: ntfy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

