apiVersion: v1
kind: Secret
metadata:
  name: garage-secrets
  namespace: garage
type: Opaque
stringData:
  rpc_secret: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
  admin_token: "bedrock-garage-admin"
